Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2023-11, with the labels that each got.

#118 feat(bugfix): Bug/bucket name
  src/common/helpers/redis-helper.ts
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
Labels: beginning-contributor

#119 feat(documentation): add badges
  README.md
Labels: star-contributor

#124 feat: add commitlint github action
  .gitattributes
  .github/workflows/commitlint.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  commitlint.config.js
  projenrc/github-workflows.ts
Labels: admired-contributor

#127 feat(docs) : update architecture diagrams in README
  src/patterns/gen-ai/aws-qa-appsync-opensearch/architecture.png
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/architecture.png
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/architecture.png
Labels: repeat-contributor
