Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2024-02, with the labels that each got.

#240 fix: reduce memorySize to context
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
Labels: star-contributor

#214 chore(patterns): Add Python snippets to constructs' patterns README files
  src/patterns/gen-ai/aws-langchain-common-layer/README.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_custom_sagemaker_endpoint.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_hugging_face.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_jumpstart.md
  src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/README.md
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/README.md
Labels: beginning-contributor

#228 chore(deps): update jsii to version 5.3
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: star-contributor

#233 feat(bedrock): agent action groups
  apidocs/classes/bedrock.Agent.md
  apidocs/classes/bedrock.AgentActionGroup.md
  apidocs/classes/bedrock.ApiSchema.md
  apidocs/classes/bedrock.InlineApiSchema.md
  apidocs/classes/bedrock.S3ApiSchema.md
  apidocs/interfaces/bedrock.AddAgentActionGroupProps.md
  apidocs/interfaces/bedrock.AgentActionGroupProps.md
  apidocs/interfaces/bedrock.ApiSchemaConfig.md
  apidocs/interfaces/bedrock.S3Identifier.md
  apidocs/modules/bedrock.md
  lambda/bedrock-custom-resources/custom_resources/__init__.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_agent_action_group.py
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/agent-action-group.ts
  src/cdk-lib/bedrock/agent.ts
  src/cdk-lib/bedrock/api-schema.ts
  src/cdk-lib/bedrock/index.ts
  test/cdk-lib/bedrock/__snapshots__/agent.test.ts.snap
  test/cdk-lib/bedrock/agent-action-group.test.ts
  test/cdk-lib/bedrock/agent.test.ts
Labels: repeat-contributor

#241 chore(doc): update documentation with new resources
  README.md
Labels: star-contributor

#244 chore: update bedrock client retrieval and aoss index creation
  apidocs/classes/LangchainCommonLayer.md
  lambda/aws-qa-appsync-opensearch/question_answering/src/llms/text_generation_llm_selector.py
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/helpers/opensearch_helper.py
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/lambda.py
  lambda/aws-summarization-appsync-stepfn/summary_generator/lambda.py
  layers/langchain-common-layer/python/genai_core/adapters/bedrock/ai21_j2.py
  layers/langchain-common-layer/python/genai_core/adapters/bedrock/claude.py
  layers/langchain-common-layer/python/genai_core/adapters/bedrock/cohere.py
  layers/langchain-common-layer/python/genai_core/adapters/bedrock/titan.py
  layers/langchain-common-layer/python/genai_core/clients.py
  src/patterns/gen-ai/aws-langchain-common-layer/index.ts
Labels: valued-contributor

#250 feat(bedrock): replace PrepareAgent with shouldPrepareAgent prop
  apidocs/classes/bedrock.Agent.md
  apidocs/interfaces/bedrock.AgentActionGroupProps.md
  apidocs/interfaces/bedrock.AgentAliasProps.md
  apidocs/interfaces/bedrock.AgentProps.md
  lambda/bedrock-custom-resources/custom_resources/__init__.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_agent.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_agent_action_group.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_agent_alias.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_agent_knowledgebase.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_datasource.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_knowledgebase.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_prepare_agent.py
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/agent-action-group.ts
  src/cdk-lib/bedrock/agent-alias.ts
  src/cdk-lib/bedrock/agent.ts
  test/cdk-lib/bedrock/__snapshots__/agent.test.ts.snap
Labels: valued-contributor

#238 feat(github): automate model generation
  .gitattributes
  .github/workflows/code-generation.yml
  .gitignore
  .npmignore
  .projen/files.json
  .projenrc.ts
  apidocs/classes/JumpStartModel.md
  projenrc/github-workflows.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-model.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-models.json
Labels: star-contributor

#259 fix(workflow): read correctly variable value
  .github/workflows/code-generation.yml
  projenrc/github-workflows.ts
Labels: star-contributor

#263 chore(github): update github workflow
  .github/workflows/code-generation.yml
  .projen/tasks.json
  .projenrc.ts
  projenrc/github-workflows.ts
Labels: star-contributor

#267 chore(github): fix code generation workflow
  .projen/tasks.json
  .projenrc.ts
Labels: star-contributor

#274 chore(sg): remove default value for volumesize property
  apidocs/classes/CustomSageMakerEndpoint.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_custom_sagemaker_endpoint.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/custom-sagemaker-endpoint.ts
Labels: star-contributor

#260 feat(construct): content generation construct
  README.md
  apidocs/README.md
  apidocs/classes/ContentGenerationAppSyncLambda.md
  apidocs/interfaces/ContentGenerationAppSyncLambdaProps.md
  docs/generative_ai_cdk_constructs.drawio
  lambda/aws-contentgen-appsync-lambda/src/Dockerfile
  lambda/aws-contentgen-appsync-lambda/src/image_generator.py
  lambda/aws-contentgen-appsync-lambda/src/lambda.py
  lambda/aws-contentgen-appsync-lambda/src/requirements.txt
  resources/gen-ai/aws-contentgen-appsync-lambda/schema.graphql
  src/index.ts
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/README.md
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/architecture.png
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/index.ts
  test/patterns/gen-ai/aws-contentgen-appsync-lambda/aws-contentgen-appsync-lambda.test.ts
Labels: admired-contributor

#287 chore(doc): update documentation with new resources
  README.md
Labels: star-contributor

#257 feat(eula): expose the eula property for SageMaker JumpStart model deployment
  .projen/deps.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  apidocs/classes/JumpStartSageMakerEndpoint.md
  apidocs/interfaces/IJumpStartModelSpec.md
  apidocs/interfaces/JumpStartSageMakerEndpointProps.md
  package.json
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_jumpstart.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/code-generation/generate-jumpstart-models.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-model.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-models.json
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-sagemaker-endpoint.ts
  test/patterns/gen-ai/aws-model-deployment-sagemaker/aws-model-deployment-sagemaker.test.ts
  yarn.lock
Labels: star-contributor

#284 feat(constructs): bring your own lambda
  .eslintrc.json
  .gitattributes
  .gitignore
  .projen/files.json
  .projenrc.ts
  apidocs/README.md
  apidocs/classes/ContentGenerationAppSyncLambda.md
  apidocs/classes/QaAppsyncOpensearch.md
  apidocs/classes/RagAppsyncStepfnOpensearch.md
  apidocs/classes/SummarizationAppsyncStepfn.md
  apidocs/interfaces/ContentGenerationAppSyncLambdaProps.md
  apidocs/interfaces/DockerLambdaCustomProps.md
  apidocs/interfaces/QaAppsyncOpensearchProps.md
  apidocs/interfaces/RagAppsyncStepfnOpensearchProps.md
  apidocs/interfaces/SummarizationAppsyncStepfnProps.md
  src/common/helpers/lambda-builder-helper.ts
  src/common/helpers/python-lambda-layer-helper.ts
  src/common/props/AdapterProps.ts
  src/common/props/DockerLambdaCustomProps.ts
  src/common/props/LangchainProps.ts
  src/index.ts
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/README.md
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/index.ts
  src/patterns/gen-ai/aws-langchain-common-layer/index.ts
  src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/README.md
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/README.md
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  test/patterns/gen-ai/aws-contentgen-appsync-lambda/aws-contentgen-appsync-lambda.test.ts
  test/patterns/gen-ai/aws-qa-appsync-opensearch/aws-qa-appsync-opensearch.test.ts
  test/patterns/gen-ai/aws-qa-appsync-opensearch/customLambda/Dockerfile
  test/patterns/gen-ai/aws-qa-appsync-opensearch/customLambda/lambda.py
Labels: star-contributor

#281 feat(documentation_website): Automated deployment
  .gitattributes
  .github/workflows/deploydocs.yml
  .github/workflows/testdeployment.yml
  .gitignore
  .npmignore
  .projen/files.json
  .projenrc.ts
Labels: repeat-contributor
