Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2024-10, with the labels that each got.

#674 feat: enable vpc endpoints for each construct
  apidocs/classes/QaAppsyncOpensearch.md
  apidocs/interfaces/QaAppsyncOpensearchProps.md
  apidocs/namespaces/amazonaurora/classes/AmazonAuroraDefaultVectorStore.md
  apidocs/namespaces/amazonaurora/interfaces/AmazonAuroraDefaultVectorStoreProps.md
  lambda/opensearch-serverless-custom-resources/custom_resources/__init__.py
  lambda/opensearch-serverless-custom-resources/custom_resources/opensearch_vpc_endpoint.py
  resources/gen-ai/aws-web-crawler-container/package-lock.json
  resources/gen-ai/aws-web-crawler-container/package.json
  src/cdk-lib/amazonaurora/aurora-default-vector-store.ts
  src/cdk-lib/opensearch-vectorindex/vector-index.ts
  src/common/helpers/custom-resource-provider-helper.ts
  src/common/helpers/opensearch-helper.ts
  src/common/helpers/vpc-helper.ts
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/index.ts
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/types.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  src/patterns/gen-ai/aws-text-to-sql/index.ts
  src/patterns/gen-ai/aws-web-crawler/index.ts
  test/cdk-lib/amazonaurora/aurora-default-vector-store.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/vpc-helper.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch-serverless.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch.test.ts
  test/patterns/gen-ai/aws-summarization-appsync-stepfn/aws-summarization-appsync-stepfn.test.ts
  test/patterns/gen-ai/aws-text-to-sql/aws-text-to-sql.test.ts
Labels: beginning-contributor

#728 chore(documentation): update readme to fix issues
  README.md
Labels: distinguished-contributor

#722 feat(construct): Bug fix for aws-contentgen-appsync-lambda and aws-summarization-appsync-stepfn construct
  README.md
  lambda/aws-contentgen-appsync-lambda/src/image_generator.py
  lambda/aws-contentgen-appsync-lambda/src/lambda.py
  lambda/aws-contentgen-appsync-lambda/src/util.py
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/README.md
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  test/patterns/gen-ai/aws-summarization-appsync-stepfn/aws-summarization-appsync-stepfn.test.ts
Labels: star-contributor

#743 chore(readme): add python code snippet for bedrock knowledge base dat…
  src/cdk-lib/bedrock/README.md
Labels: distinguished-contributor

#757 feat(vpcendpoint): added nat gateway for lambda and removed loggroup …
  package-lock.json
  src/common/helpers/vpc-helper.ts
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/vpc-helper.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch-serverless.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch.test.ts
  yarn.lock
Labels: star-contributor

#751 fix(bedrock): adopt best practices
  apidocs/namespaces/bedrock/README.md
  apidocs/namespaces/bedrock/classes/Agent.md
  apidocs/namespaces/bedrock/classes/Guardrail.md
  apidocs/namespaces/bedrock/classes/GuardrailBase.md
  apidocs/namespaces/bedrock/classes/GuardrailVersion.md
  apidocs/namespaces/bedrock/classes/SensitiveInformationPolicyConfig.md
  apidocs/namespaces/bedrock/classes/Topic.md
  apidocs/namespaces/bedrock/enumerations/CanadaSpecific.md
  apidocs/namespaces/bedrock/enumerations/ContentFilterStrength.md
  apidocs/namespaces/bedrock/enumerations/ContentFilterType.md
  apidocs/namespaces/bedrock/enumerations/ContextualGroundingFilterType.md
  apidocs/namespaces/bedrock/enumerations/Finance.md
  apidocs/namespaces/bedrock/enumerations/General.md
  apidocs/namespaces/bedrock/enumerations/GuardrailAction.md
  apidocs/namespaces/bedrock/enumerations/InformationTechnology.md
  apidocs/namespaces/bedrock/enumerations/ManagedWordFilterType.md
  apidocs/namespaces/bedrock/enumerations/PiiEntitiesConfigAction.md
  apidocs/namespaces/bedrock/enumerations/UKSpecific.md
  apidocs/namespaces/bedrock/enumerations/USASpecific.md
  apidocs/namespaces/bedrock/interfaces/ContentFilter.md
  apidocs/namespaces/bedrock/interfaces/ContextualGroundingFilter.md
  apidocs/namespaces/bedrock/interfaces/CustomTopicProps.md
  apidocs/namespaces/bedrock/interfaces/GuardrailAttributes.md
  apidocs/namespaces/bedrock/interfaces/GuardrailProps.md
  apidocs/namespaces/bedrock/interfaces/IGuardrail.md
  apidocs/namespaces/bedrock/interfaces/PIIFilter.md
  apidocs/namespaces/bedrock/interfaces/RegexFilter.md
  apidocs/namespaces/bedrock/interfaces/SensitiveInformationPolicyConfigProps.md
  apidocs/namespaces/bedrock/interfaces/TopicProps.md
  apidocs/namespaces/bedrock/namespaces/PIIType/README.md
  apidocs/namespaces/bedrock/namespaces/PIIType/enumerations/CanadaSpecific.md
  apidocs/namespaces/bedrock/namespaces/PIIType/enumerations/Finance.md
  apidocs/namespaces/bedrock/namespaces/PIIType/enumerations/General.md
  apidocs/namespaces/bedrock/namespaces/PIIType/enumerations/InformationTechnology.md
  apidocs/namespaces/bedrock/namespaces/PIIType/enumerations/UKSpecific.md
  apidocs/namespaces/bedrock/namespaces/PIIType/enumerations/USASpecific.md
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/agent.ts
  src/cdk-lib/bedrock/guardrail-version.ts
  src/cdk-lib/bedrock/guardrails.ts
  src/cdk-lib/bedrock/guardrails/guardrail-filters.ts
  src/cdk-lib/bedrock/guardrails/guardrails.ts
  src/cdk-lib/bedrock/index.ts
  src/cdk-lib/bedrock/pii-list.ts
  src/cdk-lib/bedrock/topic-list.ts
  test/cdk-lib/bedrock/agent.test.ts
  test/cdk-lib/bedrock/guardrails.test.ts
Labels: valued-contributor

#758 feat: add destroy and create options for generate physical name
  src/cdk-lib/bedrock/data-sources/s3-data-source.ts
  src/common/helpers/utils.ts
  test/common/helpers/utils.test.ts
Labels: star-contributor

#765 fix(bedrock): add Claude 3.5 v2 and remove old file
  apidocs/namespaces/bedrock/README.md
  apidocs/namespaces/bedrock/classes/BedrockFoundationModel.md
  apidocs/namespaces/bedrock/classes/ContentPolicyConfig.md
  apidocs/namespaces/bedrock/enumerations/ContextualGroundingFilterConfigType.md
  apidocs/namespaces/bedrock/enumerations/FiltersConfigStrength.md
  apidocs/namespaces/bedrock/enumerations/FiltersConfigType.md
  apidocs/namespaces/bedrock/interfaces/ContentPolicyConfigProps.md
  apidocs/namespaces/bedrock/interfaces/ContextualGroundingPolicyConfigProps.md
  src/cdk-lib/bedrock/content-policy.ts
  src/cdk-lib/bedrock/index.ts
  src/cdk-lib/bedrock/models.ts
Labels: valued-contributor
