Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2024-09, with the labels that each got.

#665 feat(bedrock): New embedding model config
  apidocs/namespaces/bedrock/README.md
  apidocs/namespaces/bedrock/classes/AgentAlias.md
  apidocs/namespaces/bedrock/classes/BedrockFoundationModel.md
  apidocs/namespaces/bedrock/interfaces/AgentAliasProps.md
  apidocs/namespaces/bedrock/interfaces/IAgentAlias.md
  src/cdk-lib/bedrock/agent-alias.ts
  src/cdk-lib/bedrock/knowledge-base.ts
  src/cdk-lib/bedrock/models.ts
  test/cdk-lib/bedrock/agent.test.ts
  test/cdk-lib/bedrock/knowledge-base.test.ts
Labels: beginning-contributor

#682 chore: add missing models (3.5 sonnet and 3 opus)
  apidocs/namespaces/bedrock/classes/BedrockFoundationModel.md
  src/cdk-lib/bedrock/models.ts
Labels: beginning-contributor

#685 feat(sagemaker): add min-maxCapacity for autoscaling of custom-sagemaker-endpoint
  apidocs/classes/CustomSageMakerEndpoint.md
  apidocs/interfaces/CustomSageMakerEndpointProps.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_custom_sagemaker_endpoint.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/custom-sagemaker-endpoint.ts
  test/patterns/gen-ai/aws-model-deployment-sagemaker/aws-custom-sagemaker-endpoint.test.ts
Labels: beginning-contributor

#701 chore(texttosql): codeql findings
  lambda/aws-text-to-sql/query_executor/db_helper.py
  lambda/aws-text-to-sql/query_generator/db_helper.py
Labels: distinguished-contributor

#692 feat(Sagemaker): allow deploying llama 3.1 from Sagemaker Jumpstart
  apidocs/interfaces/IJumpStartModelSpec.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/code-generation/generate-jumpstart-models.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-model.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-models.json
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-sagemaker-endpoint.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/private/jumpstart-constants.ts
Labels: beginning-contributor

#535 feat(java): java package
  .github/workflows/build.yml
  .github/workflows/release.yml
  .mergify.yml
  .projen/tasks.json
  .projenrc.ts
  README.md
  package.json
Labels: star-contributor

#705 fix(guardrails): typo input messaging
  src/cdk-lib/bedrock/guardrails.ts
  test/cdk-lib/bedrock/guardrails.test.ts
Labels: beginning-contributor

#707 fix(guardrail): replace mask for anonymize
  apidocs/namespaces/bedrock/enumerations/PiiEntitiesConfigAction.md
  apidocs/namespaces/bedrock/interfaces/GuardrailProps.md
  src/cdk-lib/bedrock/guardrails.ts
  src/cdk-lib/bedrock/pii-list.ts
Labels: beginning-contributor

#713 fix(tests): remove tests artifacts
  test/cdk-lib/bedrock/integ-tests/prompts.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/cdk-lib/bedrock/integ-tests/prompts.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.template.json
  test/cdk-lib/bedrock/integ-tests/prompts.integ.snapshot/aws-cdk-bedrock-prompts-integ-test.assets.json
  test/cdk-lib/bedrock/integ-tests/prompts.integ.snapshot/aws-cdk-bedrock-prompts-integ-test.template.json
  test/cdk-lib/bedrock/integ-tests/prompts.integ.snapshot/integ.json
Labels: distinguished-contributor

#715 fix(release): fix release flow
  apidocs/namespaces/bedrock/classes/SharePointDataSource.md
  apidocs/namespaces/bedrock/enumerations/SharePointDataSourceAuthType.md
  apidocs/namespaces/bedrock/enumerations/SharePointObjectType.md
  apidocs/namespaces/bedrock/interfaces/SharePointCrawlingFilters.md
  apidocs/namespaces/bedrock/interfaces/SharePointDataSourceAssociationProps.md
  apidocs/namespaces/bedrock/interfaces/SharePointDataSourceProps.md
Labels: repeat-contributor
