Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2024-06, with the labels that each got.

#486 chore(doc): udpate documentation
  README.md
  apidocs/interfaces/BaseClassProps.md
  apidocs/interfaces/ContentGenerationAppSyncLambdaProps.md
  apidocs/interfaces/CustomSageMakerEndpointProps.md
  apidocs/interfaces/HuggingFaceSageMakerEndpointProps.md
  apidocs/interfaces/JumpStartSageMakerEndpointProps.md
  apidocs/interfaces/QaAppsyncOpensearchProps.md
  apidocs/interfaces/RagAppsyncStepfnOpensearchProps.md
  apidocs/interfaces/SummarizationAppsyncStepfnProps.md
  src/common/base-class/base-class.ts
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/README.md
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/index.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/custom-sagemaker-endpoint.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/huggingface-sagemaker-endpoint.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-sagemaker-endpoint.ts
  src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/README.md
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/README.md
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  website/docs/api/interfaces/QaAppsyncOpensearchProps.md
  website/docs/api/interfaces/RagAppsyncStepfnOpensearchProps.md
  website/docs/api/interfaces/SummarizationAppsyncStepfnProps.md
  website/docs/patterns/aws-qa-appsync-opensearch/README.md
  website/docs/patterns/aws-rag-appsync-stepfn-opensearch/README.mdx
  website/docs/patterns/aws-summarization-appsync-stepfn/README.md
  website/docs/quick-start.mdx
Labels: distinguished-contributor

#493 chore(doc): fix code snippet
  src/cdk-lib/bedrock/README.md
Labels: distinguished-contributor

#466 chore(deps): fix dependabot issues
  lambda/aws-contentgen-appsync-lambda/src/requirements.txt
  lambda/aws-qa-appsync-opensearch/question_answering/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/helpers/pdf_transformer.py
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt
  lambda/aws-summarization-appsync-stepfn/document_reader/helper.py
  lambda/aws-summarization-appsync-stepfn/document_reader/requirements.txt
  lambda/aws-summarization-appsync-stepfn/document_reader/s3inmemoryloader.py
  lambda/aws-summarization-appsync-stepfn/input_validator/requirements.txt
  lambda/aws-summarization-appsync-stepfn/summary_generator/requirements.txt
  layers/langchain-common-deps/requirements.txt
Labels: distinguished-contributor

#499 chore(readme): add additional resources
  README.md
Labels: distinguished-contributor

#495 feat: Introduce Titan Text Embedding V2
  apidocs/classes/bedrock.BedrockFoundationModel.md
  src/cdk-lib/bedrock/models.ts
Labels: beginning-contributor

#512 chore(deps): update langchain community
  lambda/aws-qa-appsync-opensearch/question_answering/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt
  lambda/aws-summarization-appsync-stepfn/document_reader/requirements.txt
  lambda/aws-summarization-appsync-stepfn/summary_generator/requirements.txt
  layers/langchain-common-deps/requirements.txt
Labels: distinguished-contributor

#525 chore(actions): label dependabot PRs
  .github/dependabot.yml
  .projenrc.ts
Labels: distinguished-contributor

#529 feat(dotnet): publish constructs to NuGet
  .github/workflows/build.yml
  .github/workflows/release.yml
  .mergify.yml
  .projen/tasks.json
  .projenrc.ts
  package.json
Labels: star-contributor

#538 chore(bedrock): add support for claude sonnet 3.5 in qa
  lambda/aws-qa-appsync-opensearch/question_answering/src/llms/types.py
Labels: distinguished-contributor
