Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2024-08, with the labels that each got.

#596 fix: repolinter compliance
  .github/SECURITY.md
  .github/SUPPORT.md
  README.md
  repolinter.json
Labels: star-contributor

#605 feat: update API documentation links in README files
  src/cdk-lib/amazonaurora/README.md
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/opensearch-vectorindex/README.md
  src/cdk-lib/opensearchserverless/README.md
  src/cdk-lib/pinecone/README.md
Labels: beginning-contributor

#581 chore(deps): update langchain deps
  lambda/aws-qa-appsync-opensearch/question_answering/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt
  lambda/aws-summarization-appsync-stepfn/document_reader/requirements.txt
  lambda/aws-summarization-appsync-stepfn/summary_generator/requirements.txt
  layers/langchain-common-deps/requirements.txt
Labels: distinguished-contributor

#615 fix: update path to upload file
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/helpers/utils.py
Labels: star-contributor

#612 fix: remove files from distribution
  .npmignore
  .projenrc.ts
Labels: star-contributor

#609 fix: add badge and update README for nuget
  README.md
Labels: star-contributor

#614 chore: add vpc endpoint for each construct
  apidocs/classes/QaAppsyncOpensearch.md
  apidocs/interfaces/QaAppsyncOpensearchProps.md
  lambda/opensearch-serverless-custom-resources/custom_resources/__init__.py
  lambda/opensearch-serverless-custom-resources/custom_resources/opensearch_vpc_endpoint.py
  src/cdk-lib/amazonaurora/aurora-default-vector-store.ts
  src/common/helpers/custom-resource-provider-helper.ts
  src/common/helpers/opensearch-helper.ts
  src/common/helpers/vpc-helper.ts
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/index.ts
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/types.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  src/patterns/gen-ai/aws-web-crawler/index.ts
  test/patterns/gen-ai/aws-qa-appsync-opensearch/aws-qa-appsync-opensearch.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/vpc-helper.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch-serverless.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch.test.ts
  test/patterns/gen-ai/aws-summarization-appsync-stepfn/aws-summarization-appsync-stepfn.test.ts
  yarn.lock
Labels: beginning-contributor

#573 feat: distribute go repository
  .github/workflows/build.yml
  .github/workflows/release.yml
  .mergify.yml
  .projen/tasks.json
  .projenrc.ts
  README.md
  package.json
Labels: star-contributor

#618 fix: add package name for Go module
  .projenrc.ts
  README.md
  package.json
Labels: star-contributor

#620 Revert "chore: add vpc endpoint for each construct"
  apidocs/classes/QaAppsyncOpensearch.md
  apidocs/interfaces/QaAppsyncOpensearchProps.md
  lambda/opensearch-serverless-custom-resources/custom_resources/__init__.py
  lambda/opensearch-serverless-custom-resources/custom_resources/opensearch_vpc_endpoint.py
  src/cdk-lib/amazonaurora/aurora-default-vector-store.ts
  src/common/helpers/custom-resource-provider-helper.ts
  src/common/helpers/opensearch-helper.ts
  src/common/helpers/vpc-helper.ts
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/index.ts
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/types.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  src/patterns/gen-ai/aws-web-crawler/index.ts
  test/patterns/gen-ai/aws-qa-appsync-opensearch/aws-qa-appsync-opensearch.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/vpc-helper.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch-serverless.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch.test.ts
  test/patterns/gen-ai/aws-summarization-appsync-stepfn/aws-summarization-appsync-stepfn.test.ts
  yarn.lock
Labels: distinguished-contributor

#619 fix: changed from github go module to github tag shield
  README.md
Labels: star-contributor

#613 feat(amazonaurora): adding customization Aurora Vector Store
  apidocs/namespaces/amazonaurora/classes/AmazonAuroraDefaultVectorStore.md
  apidocs/namespaces/amazonaurora/interfaces/AmazonAuroraDefaultVectorStoreProps.md
  src/cdk-lib/amazonaurora/aurora-default-vector-store.ts
  test/cdk-lib/amazonaurora/aurora-default-vector-store.test.ts
Labels: beginning-contributor

#622 chore(documentation): Update additional resources in main readme
  README.md
Labels: distinguished-contributor

#629 chore(rag os): Update Documentation
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/README.md
Labels: distinguished-contributor

#642 fix(agent): fix enable user input bug
  src/cdk-lib/bedrock/agent.ts
  test/cdk-lib/bedrock/agent.test.ts
Labels: beginning-contributor

#651 feat(construct): add cloudwatch dashboard for bedrock
  README.md
  apidocs/README.md
  apidocs/classes/BedrockCwDashboard.md
  apidocs/interfaces/BedrockCwDashboardProps.md
  apidocs/interfaces/ModelMonitoringProps.md
  src/index.ts
  src/patterns/gen-ai/aws-bedrock-cw-dashboard/README.md
  src/patterns/gen-ai/aws-bedrock-cw-dashboard/index.ts
  test/patterns/gen-ai/aws-bedrock-cw-dashboard/aws-bedrock-cw-dashboard.test.ts
Labels: distinguished-contributor

#660 feat(guardrails): add Contextual grounding
  .projen/deps.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  apidocs/interfaces/DockerLambdaCustomProps.md
  apidocs/namespaces/bedrock/README.md
  apidocs/namespaces/bedrock/classes/Guardrail.md
  apidocs/namespaces/bedrock/enumerations/ContextualGroundingFilterConfigType.md
  apidocs/namespaces/bedrock/interfaces/ContextualGroundingPolicyConfigProps.md
  apidocs/namespaces/bedrock/interfaces/GuardrailProps.md
  package.json
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/content-policy.ts
  src/cdk-lib/bedrock/guardrails.ts
  src/common/props/DockerLambdaCustomProps.ts
  test/cdk-lib/bedrock/guardrails.test.ts
  yarn.lock
Labels: distinguished-contributor

#663 feat(bedrock): Implement Prompt management
  .eslintrc.json
  .gitignore
  .npmignore
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  apidocs/namespaces/bedrock/README.md
  apidocs/namespaces/bedrock/classes/Prompt.md
  apidocs/namespaces/bedrock/classes/PromptVariant.md
  apidocs/namespaces/bedrock/classes/PromptVersion.md
  apidocs/namespaces/bedrock/enumerations/PromptTemplateType.md
  apidocs/namespaces/bedrock/interfaces/CommonPromptVariantProps.md
  apidocs/namespaces/bedrock/interfaces/IPrompt.md
  apidocs/namespaces/bedrock/interfaces/PromptProps.md
  apidocs/namespaces/bedrock/interfaces/PromptVersionProps.md
  apidocs/namespaces/bedrock/interfaces/TextPromptVariantProps.md
  package.json
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/agent-action-group.ts
  src/cdk-lib/bedrock/guardrails.ts
  src/cdk-lib/bedrock/index.ts
  src/cdk-lib/bedrock/models.ts
  src/cdk-lib/bedrock/prompt-version.ts
  src/cdk-lib/bedrock/prompt.ts
  src/common/base-class/base-class.ts
  src/common/helpers/utils.ts
  src/common/helpers/vpc-helper.ts
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/index.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/custom-sagemaker-endpoint.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/huggingface-sagemaker-endpoint.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-sagemaker-endpoint.ts
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  test/cdk-lib/bedrock/integ-tests/prompts.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/cdk-lib/bedrock/integ-tests/prompts.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.template.json
  test/cdk-lib/bedrock/integ-tests/prompts.integ.snapshot/aws-cdk-bedrock-prompts-integ-test.assets.json
  test/cdk-lib/bedrock/integ-tests/prompts.integ.snapshot/aws-cdk-bedrock-prompts-integ-test.template.json
  test/cdk-lib/bedrock/integ-tests/prompts.integ.snapshot/integ.json
  test/cdk-lib/bedrock/integ-tests/prompts.integ.ts
  test/cdk-lib/bedrock/prompts.test.ts
  yarn.lock
Labels: beginning-contributor

#671 chore(projen): update releasable commits
  .projen/tasks.json
  .projenrc.ts
Labels: distinguished-contributor

#673 chore(projen): enable issue creation on release failure
  .github/workflows/release.yml
  .projenrc.ts
Labels: distinguished-contributor
