Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2024-05, with the labels that each got.

#422 fix: embedding_job is failing to generate embeddings
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/lambda.py
Labels: beginning-contributor

#434 fix(documentation): update python code snippet for agent alias
  src/cdk-lib/bedrock/README.md
Labels: distinguished-contributor

#435 chore(model): add support for titan premier
  apidocs/classes/bedrock.BedrockFoundationModel.md
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/titan.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/llms/types.py
  src/cdk-lib/bedrock/models.ts
Labels: distinguished-contributor

#440 feat: update README.md
  README.md
Labels: beginning-contributor

#441 fix(bedrock): fix agent version issue
  lambda/bedrock-custom-resources/custom_resources/bedrock_agent_alias.py
Labels: distinguished-contributor

#414 feat(Construct): replace custom resource with bedrock L1 constructs
  .projen/deps.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  apidocs/README.md
  apidocs/classes/bedrock.Agent.md
  apidocs/classes/bedrock.AgentActionGroup.md
  apidocs/classes/bedrock.AgentAlias.md
  apidocs/classes/bedrock.KnowledgeBase.md
  apidocs/classes/bedrock.S3DataSource.md
  apidocs/classes/pinecone.PineconeVectorStore.md
  apidocs/classes/redisenterprisecloud.RedisEnterpriseVectorStore.md
  apidocs/interfaces/DockerLambdaCustomProps.md
  apidocs/interfaces/bedrock.AddAgentActionGroupProps.md
  apidocs/interfaces/bedrock.AddAgentAliasProps.md
  apidocs/interfaces/bedrock.AgentActionGroupProps.md
  apidocs/interfaces/bedrock.AgentAliasProps.md
  apidocs/interfaces/bedrock.AgentProps.md
  apidocs/interfaces/bedrock.KnowledgeBaseProps.md
  apidocs/interfaces/pinecone.PineconeVectorStoreProps.md
  apidocs/interfaces/redisenterprisecloud.RedisEnterpriseVectorStoreProps.md
  apidocs/modules/bedrock.md
  apidocs/modules/redisenterprisecloud.md
  lambda/bedrock-custom-resources/Dockerfile
  lambda/bedrock-custom-resources/custom_resources/__init__.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_agent.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_agent_action_group.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_agent_alias.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_agent_knowledgebase.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_datasource.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_knowledgebase.py
  lambda/bedrock-custom-resources/custom_resources/bedrock_prepare_agent.py
  lambda/bedrock-custom-resources/custom_resources/cr_types.py
  lambda/bedrock-custom-resources/custom_resources/exceptions.py
  lambda/bedrock-custom-resources/poetry.lock
  lambda/bedrock-custom-resources/pyproject.toml
  lambda/opensearch-serverless-custom-resources/custom_resources/opensearch_index.py
  package.json
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/agent-action-group.ts
  src/cdk-lib/bedrock/agent-alias.ts
  src/cdk-lib/bedrock/agent.ts
  src/cdk-lib/bedrock/custom-resource-provider.ts
  src/cdk-lib/bedrock/knowledge-base.ts
  src/cdk-lib/bedrock/s3-data-source.ts
  src/cdk-lib/pinecone/README.md
  src/cdk-lib/pinecone/pinecone-vector-store.ts
  src/cdk-lib/redisenterprisecloud/README.md
  src/cdk-lib/redisenterprisecloud/index.ts
  src/cdk-lib/redisenterprisecloud/redis-enterprise-vector-store.ts
  src/common/props/DockerLambdaCustomProps.ts
  src/index.ts
  test/cdk-lib/bedrock/__snapshots__/agent.test.ts.snap
  test/cdk-lib/bedrock/agent-action-group.test.ts
  test/cdk-lib/bedrock/agent.test.ts
  test/cdk-lib/bedrock/knowledge-base.test.ts
  test/cdk-lib/bedrock/s3-data-source.test.ts
  test/cdk-lib/pinecone/pinecone-vector-store.test.ts
  test/cdk-lib/redisenterprisecloud/redis-enterprise-vector-store.test.ts
  yarn.lock
Labels: admired-contributor

#450 feat(construct): added enableUserInput prop on agent
  apidocs/interfaces/bedrock.AgentProps.md
  src/cdk-lib/bedrock/agent.ts
Labels: admired-contributor

#456 chore(doc): update redame with additional assets
  README.md
Labels: distinguished-contributor

#454 feat(bedrockconstruct): added support for IAM existingRole
  apidocs/interfaces/bedrock.AgentProps.md
  apidocs/interfaces/bedrock.KnowledgeBaseProps.md
  src/cdk-lib/bedrock/agent.ts
  src/cdk-lib/bedrock/knowledge-base.ts
Labels: star-contributor

#471 fix(bedrock): use CfnDataSource and construct's dataSourceId as unique id (fixes #470)
  apidocs/classes/bedrock.S3DataSource.md
  src/cdk-lib/bedrock/s3-data-source.ts
Labels: beginning-contributor

#472 chore(docs): update DEVELOPER_GUIDE.md
  DEVELOPER_GUIDE.md
Labels: beginning-contributor

#481 fix(bedrock): fix default chunking strategy not deploying
  apidocs/enums/bedrock.ChunkingStrategy.md
  src/cdk-lib/bedrock/s3-data-source.ts
  test/cdk-lib/bedrock/__snapshots__/agent.test.ts.snap
  test/cdk-lib/bedrock/s3-data-source.test.ts
Labels: distinguished-contributor

#473 feat(construct): Support for bedrock guardrail
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  CHANGELOG.md
  apidocs/classes/bedrock.AgentActionGroup.md
  apidocs/classes/bedrock.ContentPolicyConfig.md
  apidocs/classes/bedrock.Guardrail.md
  apidocs/classes/bedrock.GuardrailVersion.md
  apidocs/classes/bedrock.SensitiveInformationPolicyConfig.md
  apidocs/classes/bedrock.Topic.md
  apidocs/enums/bedrock.CanadaSpecific.md
  apidocs/enums/bedrock.FiltersConfigStrength.md
  apidocs/enums/bedrock.FiltersConfigType.md
  apidocs/enums/bedrock.Finance.md
  apidocs/enums/bedrock.General.md
  apidocs/enums/bedrock.InformationTechnology.md
  apidocs/enums/bedrock.PiiEntitiesConfigAction.md
  apidocs/enums/bedrock.UKSpecific.md
  apidocs/enums/bedrock.USASpecific.md
  apidocs/interfaces/bedrock.ActionGroupExecutor.md
  apidocs/interfaces/bedrock.AgentActionGroupProps.md
  apidocs/interfaces/bedrock.ContentPolicyConfigProps.md
  apidocs/interfaces/bedrock.GuardrailProps.md
  apidocs/interfaces/bedrock.SensitiveInformationPolicyConfigProps.md
  apidocs/interfaces/bedrock.TopicProps.md
  apidocs/modules/bedrock.md
  package.json
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/agent-action-group.ts
  src/cdk-lib/bedrock/agent.ts
  src/cdk-lib/bedrock/content-policy.ts
  src/cdk-lib/bedrock/guardrail-version.ts
  src/cdk-lib/bedrock/guardrails.ts
  src/cdk-lib/bedrock/index.ts
  src/cdk-lib/bedrock/pii-list.ts
  src/cdk-lib/bedrock/topic-list.ts
  test/cdk-lib/bedrock/agent-action-group.test.ts
  test/cdk-lib/bedrock/agent.test.ts
  test/cdk-lib/bedrock/guardrails.test.ts
  yarn.lock
Labels: star-contributor

#483 feat(construct): fixed issues in image summarization
  apidocs/classes/SummarizationAppsyncStepfn.md
  lambda/aws-summarization-appsync-stepfn/document_reader/helper.py
  lambda/aws-summarization-appsync-stepfn/summary_generator/lambda.py
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  test/patterns/gen-ai/aws-summarization-appsync-stepfn/aws-summarization-appsync-stepfn.test.ts
Labels: star-contributor
