Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2024-07, with the labels that each got.

#543 chore(LangchainCommonLayer): Remove construct
  .gitattributes
  .gitignore
  .projen/files.json
  .projenrc.ts
  apidocs/README.md
  apidocs/classes/LangchainCommonLayer.md
  apidocs/interfaces/AdapterProps.md
  docs/generative_ai_cdk_constructs.drawio
  src/common/props/AdapterProps.ts
  src/index.ts
  src/patterns/gen-ai/aws-langchain-common-layer/README.md
  src/patterns/gen-ai/aws-langchain-common-layer/architecture.png
  src/patterns/gen-ai/aws-langchain-common-layer/index.ts
  test/cdk-lib/bedrock/guardrails.test.ts
  test/cdk-lib/bedrock/models.test.ts
  test/cdk-lib/bedrock/s3-data-source.test.ts
  test/patterns/gen-ai/aws-contentgen-appsync-lambda/aws-contentgen-appsync-lambda.test.ts
  test/patterns/gen-ai/aws-langchain-common-layer/aws-langchain-common-layer.test.ts
  test/patterns/gen-ai/aws-model-deployment-sagemaker/aws-model-deployment-sagemaker.test.ts
  test/patterns/gen-ai/aws-qa-appsync-opensearch/aws-qa-appsync-opensearch-serverless.test.ts
  test/patterns/gen-ai/aws-qa-appsync-opensearch/aws-qa-appsync-opensearch.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/iam-helper.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/kendra-utils.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/vpc-helper.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch-serverless.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/aws-rag-appsync-stepfn-opensearch.test.ts
  test/patterns/gen-ai/aws-summarization-appsync-stepfn/aws-summarization-appsync-stepfn.test.ts
  test/patterns/gen-ai/aws-web-crawler/aws-web-crawler.test.ts
Labels: distinguished-contributor

#537 feat(opensearch serverless): analyzer
  apidocs/enums/opensearchserverless.CharacterFilterType.md
  apidocs/enums/opensearchserverless.TokenFilterType.md
  apidocs/enums/opensearchserverless.TokenizerType.md
  apidocs/interfaces/opensearch_vectorindex.Analyzer.md
  apidocs/interfaces/opensearch_vectorindex.VectorIndexProps.md
  apidocs/modules/opensearch_vectorindex.md
  apidocs/modules/opensearchserverless.md
  lambda/opensearch-serverless-custom-resources/custom_resources/opensearch_index.py
  src/cdk-lib/bedrock/knowledge-base.ts
  src/cdk-lib/opensearch-vectorindex/README.md
  src/cdk-lib/opensearch-vectorindex/vector-index.ts
  src/cdk-lib/opensearchserverless/analysis-plugins.ts
  src/cdk-lib/opensearchserverless/index.ts
  test/cdk-lib/opensearch-vectorindex/vector-index.test.ts
Labels: beginning-contributor

#545 feat(dependency): removed nltk dependency from summarization, dependa…
  lambda/aws-summarization-appsync-stepfn/summary_generator/helper.py
  lambda/aws-summarization-appsync-stepfn/summary_generator/requirements.txt
Labels: star-contributor

#555 fix: typo in documentation
  src/patterns/gen-ai/aws-web-crawler/README.md
Labels: beginning-contributor

#564 feat(bedrock): add guardrail support for agents
  .eslintrc.json
  .github/workflows/build.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .npmignore
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  CHANGELOG.md
  apidocs/interfaces/DockerLambdaCustomProps.md
  apidocs/namespaces/bedrock/README.md
  apidocs/namespaces/bedrock/classes/Agent.md
  apidocs/namespaces/bedrock/interfaces/AgentProps.md
  apidocs/namespaces/bedrock/interfaces/GuardrailConfiguration.md
  package-lock.json
  package.json
  projenrc/github-jobs.ts
  src/cdk-lib/bedrock/agent.ts
  src/common/props/DockerLambdaCustomProps.ts
  test/cdk-lib/bedrock/__snapshots__/agent.test.ts.snap
  test/cdk-lib/bedrock/agent.test.ts
  yarn.lock
Labels: distinguished-contributor

#568 feat(bugfix): updated maxlength value from 32 to 63
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
Labels: star-contributor

#579 fix(bug578): fix issue when not providing guardrails through agent constructor
  src/cdk-lib/bedrock/agent.ts
  test/cdk-lib/bedrock/__snapshots__/agent.test.ts.snap
  test/cdk-lib/bedrock/agent.test.ts
Labels: distinguished-contributor

#584 fix(doc): add notice when building on differing architectures
  layers/langchain-common-layer/python/genai_core/adapters/__init__.py
  layers/langchain-common-layer/python/genai_core/adapters/base/__init__.py
  layers/langchain-common-layer/python/genai_core/adapters/base/base.py
  layers/langchain-common-layer/python/genai_core/adapters/bedrock/__init__.py
  layers/langchain-common-layer/python/genai_core/adapters/bedrock/ai21_j2.py
  layers/langchain-common-layer/python/genai_core/adapters/bedrock/claude.py
  layers/langchain-common-layer/python/genai_core/adapters/bedrock/cohere.py
  layers/langchain-common-layer/python/genai_core/adapters/bedrock/titan.py
  layers/langchain-common-layer/python/genai_core/adapters/openai/__init__.py
  layers/langchain-common-layer/python/genai_core/adapters/openai/gpt.py
  layers/langchain-common-layer/python/genai_core/adapters/registry/__init__.py
  layers/langchain-common-layer/python/genai_core/adapters/registry/index.py
  layers/langchain-common-layer/python/genai_core/adapters/sagemaker/__init__.py
  layers/langchain-common-layer/python/genai_core/adapters/sagemaker/amazon/__init__.py
  layers/langchain-common-layer/python/genai_core/adapters/sagemaker/amazon/falconlite.py
  layers/langchain-common-layer/python/genai_core/adapters/sagemaker/meta/__init__.py
  layers/langchain-common-layer/python/genai_core/adapters/sagemaker/meta/llama2_base.py
  layers/langchain-common-layer/python/genai_core/adapters/sagemaker/meta/llama2_chat.py
  layers/langchain-common-layer/python/genai_core/clients.py
  layers/langchain-common-layer/python/genai_core/utils/__init__.py
  layers/langchain-common-layer/python/genai_core/utils/error_codes.py
  src/patterns/gen-ai/aws-langchain-common-layer/README.md
Labels: star-contributor

#591 feat(customSageMakerEndpoint): Enable Async configuration for endpoint
  apidocs/README.md
  apidocs/classes/CustomSageMakerEndpoint.md
  apidocs/interfaces/AsyncInferenceConfig.md
  apidocs/interfaces/CustomSageMakerEndpointProps.md
  docs/generative_ai_cdk_constructs.drawio
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_custom_sagemaker_endpoint.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/architecture_async_CustomSageMakerEndpoint.png
  src/patterns/gen-ai/aws-model-deployment-sagemaker/architecture_rt_CustomSageMakerEndpoint.png
  src/patterns/gen-ai/aws-model-deployment-sagemaker/custom-sagemaker-endpoint.ts
  test/patterns/gen-ai/aws-model-deployment-sagemaker/aws-custom-sagemaker-endpoint.test.ts
  test/patterns/gen-ai/aws-model-deployment-sagemaker/aws-huggingface-sagemaker-endpoint.test.ts
  test/patterns/gen-ai/aws-model-deployment-sagemaker/aws-sagemaker-jumpstart-endpoint.test.ts
Labels: distinguished-contributor
