Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2024-03, with the labels that each got.

#300 chore(construct): SageMaker JumpStart construct endpoint name update
  apidocs/interfaces/JumpStartSageMakerEndpointProps.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_jumpstart.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-sagemaker-endpoint.ts
  test/patterns/gen-ai/aws-model-deployment-sagemaker/aws-model-deployment-sagemaker.test.ts
Labels: distinguished-contributor

#307 feat(docs): better handling of dependabot updates
  .gitattributes
  .github/dependabot.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
Labels: repeat-contributor

#310 feat(versionupgrade): bump langchain version from 0.1.14 to 0.1.11
  lambda/aws-qa-appsync-opensearch/question_answering/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt
  lambda/aws-summarization-appsync-stepfn/document_reader/requirements.txt
  lambda/aws-summarization-appsync-stepfn/summary_generator/requirements.txt
Labels: admired-contributor

#254 feat(visualqa): question answer on uploaded image
  apidocs/classes/QaAppsyncOpensearch.md
  lambda/aws-qa-appsync-opensearch/question_answering/src/lambda.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/llms/__init__.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/llms/text_generation_llm_selector.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/StreamingCallbackHandler.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/chain.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/doc_qa.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/helper.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/image_qa.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/sagemaker_endpoint.py
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/helpers/image_loader.py
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/helpers/opensearch_helper.py
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/helpers/update_ingestion_status.py
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/lambda.py
  lambda/aws-rag-appsync-stepfn-opensearch/input_validation/src/lambda.py
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/helpers/image_transformer.py
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/helpers/pdf_transformer.py
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/helpers/utils.py
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/lambda.py
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt
  resources/gen-ai/aws-qa-appsync-opensearch/schema.graphql
  resources/gen-ai/aws-rag-appsync-stepfn-opensearch/schema.graphql
  src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/README.md
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
Labels: admired-contributor

#327 feat(documentation): updated main readme
  README.md
Labels: admired-contributor

#326 chore(doc): miscellaneous updates
  .gitattributes
  .github/workflows/monthly-repo-metrics.yml
  .github/workflows/update-contributors.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  README.md
  docs/generative_ai_cdk_constructs.drawio
  projenrc/github-workflows.ts
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/architecture.png
  src/patterns/gen-ai/aws-langchain-common-layer/architecture.png
  src/patterns/gen-ai/aws-model-deployment-sagemaker/architecture_CustomSageMakerEndpoint.png
  src/patterns/gen-ai/aws-model-deployment-sagemaker/architecture_HuggingFaceSageMakerEndpoint.png
  src/patterns/gen-ai/aws-model-deployment-sagemaker/architecture_JumpStartSageMakerEndpoint.png
  src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
  src/patterns/gen-ai/aws-qa-appsync-opensearch/architecture.png
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/architecture.png
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/architecture.png
Labels: distinguished-contributor

#332 chore(qa): refactor text qa to add support for additional models and fix issues
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/__init__.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/base/__init__.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/base/base.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/__init__.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/claude.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/titan.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/registry/__init__.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/registry/index.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/llms/__init__.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/llms/text_generation_llm_selector.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/llms/types.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/chain.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/doc_qa.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/helper.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/image_qa.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/requirements.txt
  resources/gen-ai/aws-qa-appsync-opensearch/schema.graphql
  resources/gen-ai/aws-rag-appsync-stepfn-opensearch/schema.graphql
  src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
Labels: distinguished-contributor

#333 feat(bugfix): fixed version error
  lambda/aws-contentgen-appsync-lambda/src/requirements.txt
Labels: admired-contributor

#338 feat(construct): fixed bugs in image generation construct
  apidocs/classes/ContentGenerationAppSyncLambda.md
  src/common/base-class/base-class.ts
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/index.ts
Labels: admired-contributor

#341 fix(qa): read properly var to fix streaming
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/base/base.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/claude.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/adapters/bedrock/titan.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/doc_qa.py
  src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
Labels: distinguished-contributor

#345 Feature/defect fixes
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/helper.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/image_qa.py
Labels: admired-contributor
