Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2024-04, with the labels that each got.

#350 fix(bedrock): create index with faiss and l2
  lambda/opensearch-serverless-custom-resources/custom_resources/opensearch_index.py
Labels: beginning-contributor

#296 feat: add kendra instance, vpc, permissioning
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  apidocs/classes/RagAppsyncStepfnOpensearch.md
  apidocs/enums/ConstructName.md
  docs/generative_ai_cdk_constructs.drawio
  fix()__fix_kendra_tests (1).patch
  lambda/aws-rag-appsync-stepfn-kendra/generate_presigned_url/src/Dockerfile
  lambda/aws-rag-appsync-stepfn-kendra/generate_presigned_url/src/generate_presigned_url.py
  lambda/aws-rag-appsync-stepfn-kendra/generate_presigned_url/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-kendra/kendra_job_manager/src/Dockerfile
  lambda/aws-rag-appsync-stepfn-kendra/kendra_job_manager/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-kendra/kendra_job_manager/src/update_job_status.py
  lambda/aws-rag-appsync-stepfn-kendra/kendra_sync/src/Dockerfile
  lambda/aws-rag-appsync-stepfn-kendra/kendra_sync/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-kendra/kendra_sync/src/start_sync.py
  lambda/aws-rag-appsync-stepfn-kendra/kendra_sync_status/src/Dockerfile
  lambda/aws-rag-appsync-stepfn-kendra/kendra_sync_status/src/check_sync_status.py
  lambda/aws-rag-appsync-stepfn-kendra/kendra_sync_status/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-kendra/start_kendra_sync_stepfn/src/Dockerfile
  lambda/aws-rag-appsync-stepfn-kendra/start_kendra_sync_stepfn/src/lambda.py
  lambda/aws-rag-appsync-stepfn-kendra/start_kendra_sync_stepfn/src/requirements.txt
  package-lock.json
  package.json
  resources/gen-ai/aws-rag-appsync-stepfn-kendra/schema.graphql
  src/common/base-class/base-class.ts
  src/common/base-class/construct-name-enum.ts
  src/common/helpers/dynamodb-helper.ts
  src/common/helpers/iam-roles-helper.ts
  src/common/helpers/kendra-construct.ts
  src/common/helpers/kendra-helper.ts
  src/common/helpers/kendra-utils.ts
  src/common/helpers/lambda-builder-helper.ts
  src/common/helpers/utils.ts
  src/common/helpers/vpc-helper.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/README.md
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/architecture.png
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/types.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  test/common/helpers/utils.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/base-class.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/iam-helper.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/kendra-utils.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/vpc-helper.test.ts
  yarn.lock
Labels: repeat-contributor

#351 feat(construct): updated summarization architecture and added support…
  apidocs/classes/SummarizationAppsyncStepfn.md
  apidocs/interfaces/SummarizationAppsyncStepfnProps.md
  docs/generative_ai_cdk_constructs.drawio
  lambda/aws-summarization-appsync-stepfn/document_reader/helper.py
  lambda/aws-summarization-appsync-stepfn/document_reader/lambda.py
  lambda/aws-summarization-appsync-stepfn/document_reader/update_summary_status.py
  lambda/aws-summarization-appsync-stepfn/input_validator/lambda.py
  lambda/aws-summarization-appsync-stepfn/input_validator/update_file_status.py
  lambda/aws-summarization-appsync-stepfn/summary_generator/StreamingCallbackHandler.py
  lambda/aws-summarization-appsync-stepfn/summary_generator/helper.py
  lambda/aws-summarization-appsync-stepfn/summary_generator/lambda.py
  lambda/aws-summarization-appsync-stepfn/summary_generator/update_summary_status.py
  resources/gen-ai/aws-summarization-appsync-stepfn/schema.graphql
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/README.md
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/architecture.png
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  test/patterns/gen-ai/aws-summarization-appsync-stepfn/aws-summarization-appsync-stepfn.test.ts
Labels: admired-contributor

#355 fix(error): increase retry attempts to mitigate policy creation race …
  lambda/opensearch-serverless-custom-resources/custom_resources/opensearch_index.py
Labels: distinguished-contributor

#358 chore(kendra): misc fixes in documentation
  README.md
  docs/generative_ai_cdk_constructs.drawio
  fix()__fix_kendra_tests (1).patch
  package-lock.json
  src/common/helpers/kendra-utils.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/README.md
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/architecture.png
Labels: distinguished-contributor

#362 fix(release): remove problematic test
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/base-class.test.ts
Labels: distinguished-contributor

#367 chore(aurora): remove circular dependency preventing python use
  apidocs/classes/amazonaurora.AmazonAuroraDefaultVectorStore.md
  apidocs/interfaces/amazonaurora.AmazonAuroraDefaultVectorStoreProps.md
  src/cdk-lib/amazonaurora/README.md
  src/cdk-lib/amazonaurora/aurora-default-vector-store.ts
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/knowledge-base.ts
  test/cdk-lib/amazonaurora/aurora-default-vector-store.test.ts
  test/cdk-lib/bedrock/knowledge-base.test.ts
Labels: distinguished-contributor

#369 chore(doc): add python code snippets for cdk-lib folder
  README.md
  apidocs/interfaces/amazonaurora.AmazonAuroraDefaultVectorStoreProps.md
  src/cdk-lib/amazonaurora/README.md
  src/cdk-lib/amazonaurora/aurora-default-vector-store.ts
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/opensearch-vectorindex/README.md
  src/cdk-lib/opensearchserverless/README.md
  src/cdk-lib/pinecone/README.md
  src/cdk-lib/redisenterprisecloud/README.md
Labels: distinguished-contributor

#372 chore(oss): increase retry attempts for index management
  lambda/opensearch-serverless-custom-resources/custom_resources/opensearch_index.py
Labels: distinguished-contributor

#381 chore(github): auto-approve automated github workflows
  .github/workflows/auto-approve.yml
  .github/workflows/code-generation.yml
  .github/workflows/monthly-repo-metrics.yml
  .github/workflows/upgrade-main.yml
  .projenrc.ts
  projenrc/github-jobs.ts
  projenrc/github-workflows.ts
Labels: distinguished-contributor

#385 chore(github): change PAT used for workflows
  .github/workflows/code-generation.yml
  .github/workflows/upgrade-main.yml
  projenrc/github-jobs.ts
  projenrc/github-workflows.ts
Labels: distinguished-contributor

#386 chore(github): fix github workflows
  .github/workflows/auto-approve.yml
  .github/workflows/code-generation.yml
  .github/workflows/upgrade-main.yml
  projenrc/github-jobs.ts
  projenrc/github-workflows.ts
Labels: distinguished-contributor

#389 fix: update actions with deprecation notice for node v16
  .github/workflows/bandit.yml
  .github/workflows/build.yml
  .github/workflows/code-generation.yml
  .github/workflows/commitlint.yml
  .github/workflows/deploydocs.yml
  .github/workflows/ort-toolkit.yml
  .github/workflows/release.yml
  .github/workflows/semgrep.yml
  .github/workflows/testdeployment.yml
  .github/workflows/upgrade-main.yml
  .projenrc.ts
  projenrc/github-jobs.ts
  projenrc/github-workflows.ts
Labels: star-contributor

#392 fix: dependabot security vulnerabilities
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt
  lambda/aws-summarization-appsync-stepfn/document_reader/requirements.txt
  website/docs/patterns/aws-langchain-common-layer/README.md
  website/docs/patterns/aws-qa-appsync-opensearch/README.md
  website/docusaurus.config.js
  website/package.json
  website/yarn.lock
Labels: star-contributor

#400 fix(deps): dependencies
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt
  lambda/aws-summarization-appsync-stepfn/document_reader/requirements.txt
Labels: distinguished-contributor

#405 chore(bedrock): add support for claude 3 models in agents for bedrock
  apidocs/classes/bedrock.BedrockFoundationModel.md
  src/cdk-lib/bedrock/models.ts
Labels: distinguished-contributor
