Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2024-11, with the labels that each got.

#785 feat(bedrock): add claude 3.5 haiku
  apidocs/namespaces/bedrock/classes/BedrockFoundationModel.md
  src/cdk-lib/bedrock/models.ts
Labels: valued-contributor

#786 chore(readme): add new additional resource
  README.md
Labels: distinguished-contributor

#794 fix(deprecation): announce deprecation of some constructs
  apidocs/classes/WebCrawler.md
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/index.ts
  src/patterns/gen-ai/aws-web-crawler/index.ts
Labels: distinguished-contributor

#809 fix: skip java build
  .github/workflows/build.yml
  .github/workflows/release.yml
  .mergify.yml
  .projen/tasks.json
  .projenrc.ts
  package.json
Labels: star-contributor

#800 feat(bedrock): add application inference profile
  .gitignore
  .npmignore
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  apidocs/interfaces/DockerLambdaCustomProps.md
  apidocs/namespaces/bedrock/README.md
  apidocs/namespaces/bedrock/classes/Agent.md
  apidocs/namespaces/bedrock/classes/ApplicationInferenceProfile.md
  apidocs/namespaces/bedrock/classes/BedrockFoundationModel.md
  apidocs/namespaces/bedrock/classes/CrossRegionInferenceProfile.md
  apidocs/namespaces/bedrock/classes/InferenceProfileBase.md
  apidocs/namespaces/bedrock/classes/PromptVariant.md
  apidocs/namespaces/bedrock/enumerations/CrossRegionInferenceProfileRegion.md
  apidocs/namespaces/bedrock/enumerations/InferenceProfileType.md
  apidocs/namespaces/bedrock/interfaces/AgentProps.md
  apidocs/namespaces/bedrock/interfaces/ApplicationInferenceProfileAttributes.md
  apidocs/namespaces/bedrock/interfaces/ApplicationInferenceProfileProps.md
  apidocs/namespaces/bedrock/interfaces/BedrockFoundationModelProps.md
  apidocs/namespaces/bedrock/interfaces/CommonPromptVariantProps.md
  apidocs/namespaces/bedrock/interfaces/CrossRegionInferenceProfileProps.md
  apidocs/namespaces/bedrock/interfaces/FoundationModelParsingStategyProps.md
  apidocs/namespaces/bedrock/interfaces/IInferenceProfile.md
  apidocs/namespaces/bedrock/interfaces/IInvokable.md
  apidocs/namespaces/bedrock/interfaces/TextPromptVariantProps.md
  package.json
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/agent.ts
  src/cdk-lib/bedrock/data-sources/parsing.ts
  src/cdk-lib/bedrock/index.ts
  src/cdk-lib/bedrock/inference-profiles/application-inference-profile.ts
  src/cdk-lib/bedrock/inference-profiles/common.ts
  src/cdk-lib/bedrock/inference-profiles/cross-region-inference-profile.ts
  src/cdk-lib/bedrock/models.ts
  src/cdk-lib/bedrock/prompts/prompt.ts
  src/common/props/DockerLambdaCustomProps.ts
  test/cdk-lib/bedrock/agent.test.ts
  test/cdk-lib/bedrock/data-sources/s3-data-source.test.ts
  test/cdk-lib/bedrock/inference-profile.test.ts
  test/cdk-lib/bedrock/models.test.ts
  test/cdk-lib/bedrock/prompts.test.ts
  test/integ/inference-profiles.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/integ/inference-profiles.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.template.json
  test/integ/inference-profiles.integ.snapshot/aws-cdk-bedrock-guardrails-integ-test.assets.json
  test/integ/inference-profiles.integ.snapshot/aws-cdk-bedrock-guardrails-integ-test.template.json
  test/integ/inference-profiles.integ.snapshot/integ.json
  test/integ/inference-profiles.integ.ts
  yarn.lock
Labels: distinguished-contributor

#811 feat(issue-667): added an optional custom policy for vector collection
  apidocs/namespaces/opensearchserverless/interfaces/VectorCollectionProps.md
  src/cdk-lib/opensearchserverless/vector-collection.ts
Labels: star-contributor

#817 chore(lib): remove deprecated constructs
  README.md
  apidocs/README.md
  apidocs/classes/BaseClass.md
  apidocs/classes/WebCrawler.md
  apidocs/enumerations/ConstructName.md
  apidocs/enumerations/CrawlerTargetType.md
  apidocs/interfaces/CrawlerTarget.md
  apidocs/interfaces/WebCrawlerProps.md
  src/common/base-class/construct-name-enum.ts
  src/common/helpers/kendra-construct.ts
  src/common/helpers/kendra-helper.ts
  src/common/helpers/kendra-utils.ts
  src/common/helpers/utils.ts
  src/common/helpers/vpc-helper.ts
  src/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/README.md
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/architecture.png
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/types.ts
  src/patterns/gen-ai/aws-web-crawler/README.md
  src/patterns/gen-ai/aws-web-crawler/architecture.png
  src/patterns/gen-ai/aws-web-crawler/index.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/iam-helper.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/kendra-utils.test.ts
  test/patterns/gen-ai/aws-rag-appsync-stepfn-kendra/vpc-helper.test.ts
  test/patterns/gen-ai/aws-web-crawler/aws-web-crawler.test.ts
Labels: distinguished-contributor

#821 fix: fix SQL Injection issue
  lambda/amazon-aurora-pgvector-custom-resources/custom_resources/amazon_aurora_pgvector.py
Labels: beginning-contributor

#825 chore(deprecation): update doc and remove resources
  docs/generative_ai_cdk_constructs.drawio
  lambda/aws-web-crawler-lambda/.dockerignore
  lambda/aws-web-crawler-lambda/Dockerfile
  lambda/aws-web-crawler-lambda/action-group.yaml
  lambda/aws-web-crawler-lambda/crawler.ts
  lambda/aws-web-crawler-lambda/index.ts
  lambda/aws-web-crawler-lambda/package-lock.json
  lambda/aws-web-crawler-lambda/package.json
  lambda/aws-web-crawler-lambda/tsconfig.json
  lambda/aws-web-crawler-lambda/types.ts
  lambda/aws-web-crawler-scheduler/lambda.py
  resources/gen-ai/aws-web-crawler-container/.dockerignore
  resources/gen-ai/aws-web-crawler-container/Dockerfile
  resources/gen-ai/aws-web-crawler-container/package-lock.json
  resources/gen-ai/aws-web-crawler-container/package.json
  resources/gen-ai/aws-web-crawler-container/scripts/download_files.py
  resources/gen-ai/aws-web-crawler-container/scripts/parse_html.py
  resources/gen-ai/aws-web-crawler-container/scripts/requirements.txt
  resources/gen-ai/aws-web-crawler-container/src/common/content-types.ts
  resources/gen-ai/aws-web-crawler-container/src/common/script-runner.ts
  resources/gen-ai/aws-web-crawler-container/src/crawler.ts
  resources/gen-ai/aws-web-crawler-container/src/feed-parser.ts
  resources/gen-ai/aws-web-crawler-container/src/main.ts
  resources/gen-ai/aws-web-crawler-container/src/managers/config-manager.ts
  resources/gen-ai/aws-web-crawler-container/src/managers/dynamodb-manager.ts
  resources/gen-ai/aws-web-crawler-container/src/managers/s3storage-manager.ts
  resources/gen-ai/aws-web-crawler-container/src/managers/sns-manager.ts
  resources/gen-ai/aws-web-crawler-container/src/types.ts
  resources/gen-ai/aws-web-crawler-container/src/utils.ts
  resources/gen-ai/aws-web-crawler-container/tsconfig.json
Labels: distinguished-contributor

#829 feat(cw): update bedrock cloudwatch dashboard
  apidocs/classes/BedrockCwDashboard.md
  apidocs/interfaces/ModelMonitoringProps.md
  src/patterns/gen-ai/aws-bedrock-cw-dashboard/README.md
  src/patterns/gen-ai/aws-bedrock-cw-dashboard/index.ts
Labels: distinguished-contributor
