Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2024-01, with the labels that each got.

#173 chore: upgrading package versions
  layers/langchain-common-deps/requirements.txt
Labels: beginning-contributor

#180 feat(construct): new construct for deployment of custom models to sagemaker
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  README.md
  docs/generative_ai_cdk_constructs.drawio
  package.json
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_custom_sagemaker_endpoint.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_hugging_face.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_jumpstart.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/architecture.png
  src/patterns/gen-ai/aws-model-deployment-sagemaker/architecture_CustomSageMakerEndpoint.png
  src/patterns/gen-ai/aws-model-deployment-sagemaker/architecture_HuggingFaceSageMakerEndpoint.png
  src/patterns/gen-ai/aws-model-deployment-sagemaker/architecture_JumpStartSageMakerEndpoint.png
  src/patterns/gen-ai/aws-model-deployment-sagemaker/custom-sagemaker-endpoint.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/index.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-model.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-models.json
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-sagemaker-endpoint.ts
  test/patterns/gen-ai/aws-model-deployment-sagemaker/aws-model-deployment-sagemaker.test.ts
  yarn.lock
Labels: star-contributor

#187 fix: use definition instead of schema
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
Labels: admired-contributor

#189 feat: add husky with a conventional commit check
  .husky/commit-msg
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: admired-contributor

#190 fix(doc): Update README.md
  README.md
Labels: star-contributor

#192 fix: do not require husky downstream
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: star-contributor

#191 chore(doc): Update README_custom_sagemaker_endpoint.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_custom_sagemaker_endpoint.md
Labels: star-contributor

#196 fix(utils): generatephysicalname handles short names
  src/common/helpers/utils.ts
  test/common/helpers/utils.test.ts
Labels: beginning-contributor

#176 feat(qa construct): add optional long context window approach
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/chain.py
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/lambda.py
  resources/gen-ai/aws-qa-appsync-opensearch/schema.graphql
  src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
Labels: beginning-contributor

#193 feat: clip memory for Lambda if it exceeds context
  src/common/helpers/utils.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  test/common/helpers/utils.test.ts
Labels: star-contributor

#203 fix: update lambdaMemorySizeLimiter title and comments
  test/common/helpers/utils.test.ts
Labels: star-contributor

#208 feat(sg models): expose vpc config prop
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_custom_sagemaker_endpoint.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_hugging_face.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_jumpstart.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/custom-sagemaker-endpoint.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/huggingface-sagemaker-endpoint.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-model.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-models.json
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-sagemaker-endpoint.ts
  test/patterns/gen-ai/aws-model-deployment-sagemaker/aws-model-deployment-sagemaker.test.ts
Labels: star-contributor

#205 feat(layer): use local host to install requirements
  src/common/helpers/python-lambda-layer-helper.ts
  src/patterns/gen-ai/aws-langchain-common-layer/README.md
  src/patterns/gen-ai/aws-langchain-common-layer/index.ts
Labels: beginning-contributor

#211 fix: update cdk lib to 2.116.0
  .projen/deps.json
  .projenrc.ts
  CHANGELOG.md
  package.json
  yarn.lock
Labels: star-contributor

#198 feat(claudeup): upgrade claude to use 2.1
  README.md
  lambda/aws-qa-appsync-opensearch/question_answering/src/llms/text_generation_llm_selector.py
  lambda/aws-summarization-appsync-stepfn/summary_generator/lambda.py
  src/patterns/gen-ai/aws-langchain-common-layer/README.md
  src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/README.md
Labels: beginning-contributor

#213 fix(documentation): use enum for responseGenerationMethod in example
  src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
Labels: star-contributor

#216 feat: Layer Types and Additional Packages
  .eslintrc.json
  .gitattributes
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  src/common/helpers/python-lambda-layer-helper.ts
  src/index.ts
  src/patterns/gen-ai/aws-langchain-common-layer/AdapterProps.ts
  src/patterns/gen-ai/aws-langchain-common-layer/LangchainProps.ts
  src/patterns/gen-ai/aws-langchain-common-layer/README.md
  src/patterns/gen-ai/aws-langchain-common-layer/index.ts
  yarn.lock
Labels: repeat-contributor

#219 chore(doc): Update README.md
  README.md
Labels: star-contributor

#218 fix(models): fix issue for python to synth Jumpstart and HuggingFace models constructs
  apidocs/README.md
  apidocs/classes/HuggingFaceSageMakerEndpoint.md
  apidocs/classes/JumpStartSageMakerEndpoint.md
  apidocs/interfaces/HuggingFaceSageMakerEndpointProps.md
  apidocs/interfaces/IHuggingFaceSageMakerEndpointProps.md
  apidocs/interfaces/IJumpStartSageMakerEndpointProps.md
  apidocs/interfaces/JumpStartSageMakerEndpointProps.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_hugging_face.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_jumpstart.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/huggingface-sagemaker-endpoint.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-sagemaker-endpoint.ts
Labels: star-contributor

#222 fix: update aoss resources
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/helper.py
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/lambda.py
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
Labels: repeat-contributor

#227 fix(lambda layer): fix wrong path preventing deployment
  src/patterns/gen-ai/aws-langchain-common-layer/README.md
  src/patterns/gen-ai/aws-langchain-common-layer/index.ts
  test/patterns/gen-ai/aws-langchain-common-layer/aws-langchain-common-layer.test.ts
Labels: star-contributor

#226 chore(deps): upgrade dependencies
  lambda/aws-qa-appsync-opensearch/question_answering/src/llms/text_generation_llm_selector.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/chain.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/qa_agent/helper.py
  lambda/aws-qa-appsync-opensearch/question_answering/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/helpers/opensearch_helper.py
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/lambda.py
  lambda/aws-rag-appsync-stepfn-opensearch/embeddings_job/src/requirements.txt
  lambda/aws-rag-appsync-stepfn-opensearch/s3_file_transformer/src/requirements.txt
  lambda/aws-summarization-appsync-stepfn/document_reader/requirements.txt
  lambda/aws-summarization-appsync-stepfn/summary_generator/lambda.py
  lambda/aws-summarization-appsync-stepfn/summary_generator/requirements.txt
  layers/langchain-common-deps/requirements.txt
  layers/langchain-common-layer/python/genai_core/adapters/base/base.py
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
Labels: valued-contributor

#231 feat(bedrock): method to add deps to PrepareAgent
  apidocs/classes/bedrock.Agent.md
  src/cdk-lib/bedrock/agent.ts
  test/cdk-lib/bedrock/__snapshots__/agent.test.ts.snap
Labels: repeat-contributor

#232 fix(bedrock): fix addAlias props
  apidocs/classes/bedrock.Agent.md
  apidocs/interfaces/bedrock.AddAgentAliasProps.md
  apidocs/modules/bedrock.md
  src/cdk-lib/bedrock/agent.ts
Labels: repeat-contributor
