Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2025-01, with the labels that each got.

#882 feat(bedrock): add default prompt router
  .gitignore
  .npmignore
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  apidocs/namespaces/bedrock/README.md
  apidocs/namespaces/bedrock/classes/BedrockFoundationModel.md
  apidocs/namespaces/bedrock/classes/DefaultPromptRouterIdentifier.md
  apidocs/namespaces/bedrock/classes/PromptRouter.md
  apidocs/namespaces/bedrock/interfaces/IPromptRouter.md
  apidocs/namespaces/bedrock/interfaces/PromptRouterProps.md
  apidocs/namespaces/bedrock/variables/REGION_TO_GEO_AREA.md
  package.json
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/index.ts
  src/cdk-lib/bedrock/inference-profiles/cross-region-inference-profile.ts
  src/cdk-lib/bedrock/inference-profiles/default-prompt-routers.ts
  src/cdk-lib/bedrock/models.ts
  test/integ/prompt-router.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/integ/prompt-router.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.template.json
  test/integ/prompt-router.integ.snapshot/aws-cdk-bedrock-prompt-router-integ-test.assets.json
  test/integ/prompt-router.integ.snapshot/aws-cdk-bedrock-prompt-router-integ-test.template.json
  test/integ/prompt-router.integ.snapshot/integ.json
  test/integ/prompt-router.integ.ts
  yarn.lock
Labels: valued-contributor

#898 chore(deps): upgrade cdk version following dependabot finding
  .projen/deps.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  package-lock.json
  package.json
  yarn.lock
Labels: distinguished-contributor

#909 chore(deps): add dependency to resource for CRIS
  src/cdk-lib/bedrock/agents/agent.ts
  test/integ/inference-profiles.integ.snapshot/aws-cdk-bedrock-guardrails-integ-test.assets.json
  test/integ/inference-profiles.integ.snapshot/aws-cdk-bedrock-guardrails-integ-test.template.json
  test/integ/issue747.integ.snapshot/aws-cdk-bedrock-agents-integ-test.assets.json
  test/integ/issue747.integ.snapshot/aws-cdk-bedrock-agents-integ-test.template.json
Labels: distinguished-contributor

#904 feat: use node 22
  .projenrc.ts
  package.json
Labels: star-contributor

#915 chore(cdk): upgrade cdk version to 2.177.0
  .projen/deps.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  package.json
  yarn.lock
Labels: distinguished-contributor

#924 chore(documentation): updated bedrock readme file
  src/cdk-lib/bedrock/README.md
Labels: star-contributor
