Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2025-02, with the labels that each got.

#935 chore(deprecation): deprecation announcement l3
  src/cdk-lib/amazonaurora/README.md
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/opensearch-vectorindex/README.md
  src/cdk-lib/opensearchserverless/README.md
  src/cdk-lib/pinecone/README.md
  src/patterns/gen-ai/aws-aoss-cw-dashboard/README.md
  src/patterns/gen-ai/aws-bedrock-cw-dashboard/README.md
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/README.md
  src/patterns/gen-ai/aws-contentgen-appsync-lambda/index.ts
  src/patterns/gen-ai/aws-llama-index-data-loader/index.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_custom_sagemaker_endpoint.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_hugging_face.md
  src/patterns/gen-ai/aws-model-deployment-sagemaker/README_jumpstart.md
  src/patterns/gen-ai/aws-qa-appsync-opensearch/README.md
  src/patterns/gen-ai/aws-qa-appsync-opensearch/index.ts
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/README.md
  src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/index.ts
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/README.md
  src/patterns/gen-ai/aws-summarization-appsync-stepfn/index.ts
  src/patterns/gen-ai/aws-text-to-sql/README.md
  src/patterns/gen-ai/aws-text-to-sql/index.ts
Labels: distinguished-contributor

#928 feat(construct): bedrock batch step functions fragment
  README.md
  apidocs/README.md
  apidocs/classes/BedrockBatchSfn.md
  apidocs/interfaces/BedrockBatchSfnProps.md
  lambda/aws-bedrock-batch-stepfn/.dockerignore
  lambda/aws-bedrock-batch-stepfn/.gitignore
  lambda/aws-bedrock-batch-stepfn/Dockerfile
  lambda/aws-bedrock-batch-stepfn/README.md
  lambda/aws-bedrock-batch-stepfn/pyproject.toml
  lambda/aws-bedrock-batch-stepfn/src/aws_bedrock_batch_sfn/BedrockBatch/__init__.py
  lambda/aws-bedrock-batch-stepfn/src/aws_bedrock_batch_sfn/BedrockBatch/event_handler.py
  lambda/aws-bedrock-batch-stepfn/src/aws_bedrock_batch_sfn/StepFunctions/__init__.py
  lambda/aws-bedrock-batch-stepfn/src/aws_bedrock_batch_sfn/StepFunctions/task_token_tags.py
  lambda/aws-bedrock-batch-stepfn/src/aws_bedrock_batch_sfn/__init__.py
  lambda/aws-bedrock-batch-stepfn/src/aws_bedrock_batch_sfn/bedrock_create_model_invocation_job.py
  lambda/aws-bedrock-batch-stepfn/src/aws_bedrock_batch_sfn/bedrock_inference_job_event.py
  lambda/aws-bedrock-batch-stepfn/tests/BedrockBatch/__init__.py
  lambda/aws-bedrock-batch-stepfn/tests/BedrockBatch/test_event_handler.py
  lambda/aws-bedrock-batch-stepfn/tests/StepFunctions/__init__.py
  lambda/aws-bedrock-batch-stepfn/tests/StepFunctions/test_task_token_tags.py
  lambda/aws-bedrock-batch-stepfn/tests/__init__.py
  lambda/aws-bedrock-batch-stepfn/tests/lambda_handlers/__init__.py
  lambda/aws-bedrock-batch-stepfn/tests/lambda_handlers/test_bedrock_inference_job_event.py
  lambda/aws-bedrock-batch-stepfn/uv.lock
  src/index.ts
  src/patterns/gen-ai/aws-bedrock-batch-stepfn/AUTHORS
  src/patterns/gen-ai/aws-bedrock-batch-stepfn/README.md
  src/patterns/gen-ai/aws-bedrock-batch-stepfn/architecture.png
  src/patterns/gen-ai/aws-bedrock-batch-stepfn/bedrock-batch-sfn-lambda-code.ts
  src/patterns/gen-ai/aws-bedrock-batch-stepfn/bedrock-inference-job-event-handler.ts
  src/patterns/gen-ai/aws-bedrock-batch-stepfn/create-model-invocation-job-function.ts
  src/patterns/gen-ai/aws-bedrock-batch-stepfn/index.ts
  test/patterns/gen-ai/aws-bedrock-batch-stepfn/aws-bedrock-batch-sfn.test.ts
Labels: valued-contributor

#946 Update guardrail-filters.ts
  apidocs/namespaces/bedrock/classes/Topic.md
  src/cdk-lib/bedrock/guardrails/guardrail-filters.ts
Labels: beginning-contributor

#949 chore(knowledgebase): add support for vector type
  .projen/deps.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  apidocs/namespaces/bedrock/README.md
  apidocs/namespaces/bedrock/classes/BedrockFoundationModel.md
  apidocs/namespaces/bedrock/enumerations/VectorType.md
  apidocs/namespaces/bedrock/interfaces/BedrockFoundationModelProps.md
  apidocs/namespaces/bedrock/interfaces/VectorKnowledgeBaseProps.md
  apidocs/namespaces/opensearch_vectorindex/interfaces/VectorIndexProps.md
  lambda/opensearch-serverless-custom-resources/custom_resources/opensearch_index.py
  lambda/opensearch-serverless-custom-resources/poetry.lock
  package.json
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/knowledge-bases/vector-knowledge-base.ts
  src/cdk-lib/bedrock/models.ts
  src/cdk-lib/opensearch-vectorindex/README.md
  src/cdk-lib/opensearch-vectorindex/vector-index.ts
  test/cdk-lib/bedrock/knowledge-base.test.ts
  test/cdk-lib/opensearch-vectorindex/vector-index.test.ts
  yarn.lock
Labels: distinguished-contributor

#955 chore(agent): fix issue with agent alias
  apidocs/namespaces/bedrock/interfaces/AgentAliasProps.md
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/agents/agent-alias.ts
Labels: distinguished-contributor

#958 chore(PR): doc update and code generation issue
  .github/workflows/code-generation.yml
  .projenrc.ts
  CONTRIBUTING.md
  DEPRECATION_PROCESS.md
  DESIGN_GUIDELINES.md
  DEVELOPER_GUIDE.md
  README.md
  projenrc/github-workflows.ts
Labels: distinguished-contributor

#941 feat(bedrock): add Guardrail monitoring
  .gitignore
  .npmignore
  .projen/tasks.json
  apidocs/classes/BedrockCwDashboard.md
  apidocs/namespaces/bedrock/classes/Guardrail.md
  apidocs/namespaces/bedrock/classes/GuardrailBase.md
  apidocs/namespaces/bedrock/interfaces/IGuardrail.md
  package.json
  src/cdk-lib/bedrock/guardrails/guardrails.ts
  src/patterns/gen-ai/aws-bedrock-cw-dashboard/index.ts
  test/integ/guardrails.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/integ/guardrails.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.template.json
  test/integ/guardrails.integ.snapshot/aws-cdk-bedrock-agents-integ-test.assets.json
  test/integ/guardrails.integ.snapshot/aws-cdk-bedrock-agents-integ-test.template.json
  test/integ/guardrails.integ.snapshot/integ.json
  test/integ/guardrails.integ.ts
Labels: admired-contributor

#977 chore(issues): add new templates to for issues
  .github/ISSUE_TEMPLATE/rfc.yml
  .github/ISSUE_TEMPLATE/support_genai_cdk_constructs.yml
Labels: distinguished-contributor

#994 fix(bedrock): inference profiles permissions
  .gitignore
  .npmignore
  .projen/tasks.json
  apidocs/namespaces/bedrock/classes/BedrockFoundationModel.md
  package.json
  src/cdk-lib/bedrock/inference-profiles/cross-region-inference-profile.ts
  src/cdk-lib/bedrock/models.ts
  test/integ/inference-profiles.integ.snapshot/aws-cdk-bedrock-guardrails-integ-test.assets.json
  test/integ/inference-profiles.integ.snapshot/aws-cdk-bedrock-guardrails-integ-test.template.json
  test/integ/issue747.integ.snapshot/aws-cdk-bedrock-agents-integ-test.assets.json
  test/integ/issue747.integ.snapshot/aws-cdk-bedrock-agents-integ-test.template.json
  test/integ/issue991.integ.snapshot/Claude37Test.assets.json
  test/integ/issue991.integ.snapshot/Claude37Test.template.json
  test/integ/issue991.integ.snapshot/Claude37TestIntegDefaultTestDeployAssert7B904896.assets.json
  test/integ/issue991.integ.snapshot/Claude37TestIntegDefaultTestDeployAssert7B904896.template.json
  test/integ/issue991.integ.snapshot/cdk.out
  test/integ/issue991.integ.snapshot/integ.json
  test/integ/issue991.integ.snapshot/manifest.json
  test/integ/issue991.integ.snapshot/tree.json
  test/integ/issue991.integ.ts
Labels: admired-contributor
