Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2025-03, with the labels that each got.

#1000 feat(bedrock): update cdk version + agent memory
  .gitignore
  .npmignore
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  apidocs/namespaces/bedrock/README.md
  apidocs/namespaces/bedrock/classes/Agent.md
  apidocs/namespaces/bedrock/classes/Memory.md
  apidocs/namespaces/bedrock/enumerations/AgentStepType.md
  apidocs/namespaces/bedrock/interfaces/AgentProps.md
  apidocs/namespaces/bedrock/interfaces/SessionSummaryMemoryProps.md
  package.json
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/agents/agent.ts
  src/cdk-lib/bedrock/agents/memory.ts
  src/cdk-lib/bedrock/agents/prompt-override.ts
  src/cdk-lib/bedrock/index.ts
  test/cdk-lib/bedrock/agents/agent.test.ts
  test/integ/agent-mem.integ.snapshot/AgentMemoryTest.assets.json
  test/integ/agent-mem.integ.snapshot/AgentMemoryTest.template.json
  test/integ/agent-mem.integ.snapshot/AgentMemoryTestIntegDefaultTestDeployAssertA6B9969F.assets.json
  test/integ/agent-mem.integ.snapshot/AgentMemoryTestIntegDefaultTestDeployAssertA6B9969F.template.json
  test/integ/agent-mem.integ.snapshot/integ.json
  test/integ/agent-mem.integ.ts
  yarn.lock
Labels: admired-contributor

#981 chore(aurora): aurora bug fix and readme misc updates
  README.md
  apidocs/namespaces/amazonaurora/interfaces/AmazonAuroraVectorStoreProps.md
  apidocs/namespaces/bedrock/classes/BedrockFoundationModel.md
  apidocs/namespaces/bedrock/interfaces/BedrockFoundationModelProps.md
  lambda/amazon-aurora-pgvector-custom-resources/custom_resources/amazon_aurora_pgvector.py
  src/cdk-lib/amazonaurora/README.md
  src/cdk-lib/amazonaurora/aurora-vector-store.ts
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/models.ts
Labels: distinguished-contributor

#954 feat(Construct): Bedrock Data Automation construct
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  README.md
  apidocs/README.md
  apidocs/classes/BaseClass.md
  apidocs/classes/BedrockDataAutomation.md
  apidocs/interfaces/BedrockDataAutomationProps.md
  lambda/aws-bedrock-data-automation/bda_blueprint/create_blueprint_version.py
  lambda/aws-bedrock-data-automation/bda_blueprint/create_schema.py
  lambda/aws-bedrock-data-automation/bda_blueprint/custom_blueprint_schema.py
  lambda/aws-bedrock-data-automation/bda_blueprint/lambda.py
  lambda/aws-bedrock-data-automation/bda_blueprint/manage_blueprint.py
  lambda/aws-bedrock-data-automation/bda_project/lambda.py
  lambda/aws-bedrock-data-automation/bda_project/manage_project.py
  lambda/aws-bedrock-data-automation/bda_project/project_config.py
  lambda/aws-bedrock-data-automation/data_processing/data_processing.py
  lambda/aws-bedrock-data-automation/data_processing/lambda.py
  lambda/aws-bedrock-data-automation/data_result/data_automation_result.py
  lambda/aws-bedrock-data-automation/data_result/lambda.py
  layer/requirements.txt
  package.json
  src/index.ts
  src/patterns/gen-ai/aws-bedrock-data-automation/README.md
  src/patterns/gen-ai/aws-bedrock-data-automation/architecture.png
  src/patterns/gen-ai/aws-bedrock-data-automation/bda-blueprint-lambda.ts
  src/patterns/gen-ai/aws-bedrock-data-automation/bda-data-processing-lambda.ts
  src/patterns/gen-ai/aws-bedrock-data-automation/bda-project-lambda.ts
  src/patterns/gen-ai/aws-bedrock-data-automation/bda-results-lambda.ts
  src/patterns/gen-ai/aws-bedrock-data-automation/index.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/code-generation/generate-dlc-container-images.ts
  src/patterns/gen-ai/aws-model-deployment-sagemaker/code-generation/generate-jumpstart-models.ts
  test/patterns/gen-ai/aws-bedrock-data-automation/aws-bedrock-data-automation-test.ts
  yarn.lock
Labels: star-contributor

#1011 feat(agent): add support for agent collab, orch and FM in prompt
  apidocs/namespaces/bedrock/README.md
  apidocs/namespaces/bedrock/classes/Agent.md
  apidocs/namespaces/bedrock/classes/AgentAlias.md
  apidocs/namespaces/bedrock/classes/AgentAliasBase.md
  apidocs/namespaces/bedrock/classes/AgentCollaborator.md
  apidocs/namespaces/bedrock/classes/OrchestrationExecutor.md
  apidocs/namespaces/bedrock/enumerations/AgentCollaboratorType.md
  apidocs/namespaces/bedrock/enumerations/OrchestrationType.md
  apidocs/namespaces/bedrock/enumerations/RelayConversationHistoryType.md
  apidocs/namespaces/bedrock/interfaces/AgentCollaboratorProps.md
  apidocs/namespaces/bedrock/interfaces/AgentProps.md
  apidocs/namespaces/bedrock/interfaces/CustomOrchestration.md
  apidocs/namespaces/bedrock/interfaces/IAgentAlias.md
  apidocs/namespaces/bedrock/interfaces/PromptStepConfiguration.md
  apidocs/namespaces/bedrock/interfaces/PromptStepConfigurationCustomParser.md
  apidocs/namespaces/bedrock/interfaces/SessionSummaryMemoryProps.md
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/agents/agent-alias.ts
  src/cdk-lib/bedrock/agents/agent-collaborator.ts
  src/cdk-lib/bedrock/agents/agent.ts
  src/cdk-lib/bedrock/agents/memory.ts
  src/cdk-lib/bedrock/agents/orchestration-executor.ts
  src/cdk-lib/bedrock/agents/orchestration.ts
  src/cdk-lib/bedrock/agents/prompt-override.ts
  src/cdk-lib/bedrock/index.ts
  test/cdk-lib/bedrock/agents/agent.test.ts
Labels: distinguished-contributor

#1036 feat(doc): add a link to the Terraform Registry for Bedrock
  README.md
Labels: star-contributor

#1042 feat(oss): add nori identifiers
  apidocs/namespaces/opensearchserverless/enumerations/TokenFilterType.md
  apidocs/namespaces/opensearchserverless/enumerations/TokenizerType.md
  src/cdk-lib/opensearchserverless/analysis-plugins.ts
Labels: admired-contributor
