Repository awslabs/generative-ai-cdk-constructs, pull requests merged in 2025-04, with the labels that each got.

#1051 feat(bedrock): add context enrichment and upgrade CDK
  .projen/deps.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  apidocs/@cdklabs/namespaces/bedrock/README.md
  apidocs/@cdklabs/namespaces/bedrock/classes/ContextEnrichment.md
  apidocs/@cdklabs/namespaces/bedrock/classes/WebCrawlerDataSource.md
  apidocs/@cdklabs/namespaces/bedrock/enumerations/ContextEnrichmentType.md
  apidocs/@cdklabs/namespaces/bedrock/enumerations/EnrichmentStrategyConfigurationType.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/ConfluenceDataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/ConfluenceDataSourceProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/CustomDataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/CustomDataSourceProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/DataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/FoundationModelContextEnrichmentProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/S3DataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/S3DataSourceProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/SalesforceDataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/SalesforceDataSourceProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/SharePointDataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/SharePointDataSourceProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/WebCrawlerDataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/WebCrawlerDataSourceProps.md
  package.json
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/data-sources/base-data-source.ts
  src/cdk-lib/bedrock/data-sources/context-enrichment.ts
  src/cdk-lib/bedrock/data-sources/web-crawler-data-source.ts
  src/cdk-lib/bedrock/index.ts
  test/integ/agent-mem.integ.snapshot/AgentMemoryTest.assets.json
  test/integ/agent-mem.integ.snapshot/AgentMemoryTestIntegDefaultTestDeployAssertA6B9969F.assets.json
  test/integ/agent-mem.integ.snapshot/integ.json
  test/integ/chatprompt.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/integ/chatprompt.integ.snapshot/aws-cdk-bedrock-chat-prompts-integ-test.assets.json
  test/integ/chatprompt.integ.snapshot/integ.json
  test/integ/guardrails.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/integ/guardrails.integ.snapshot/aws-cdk-bedrock-agents-integ-test.assets.json
  test/integ/guardrails.integ.snapshot/integ.json
  test/integ/inference-profiles.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/integ/inference-profiles.integ.snapshot/aws-cdk-bedrock-guardrails-integ-test.assets.json
  test/integ/inference-profiles.integ.snapshot/integ.json
  test/integ/issue747.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/integ/issue747.integ.snapshot/aws-cdk-bedrock-agents-integ-test.assets.json
  test/integ/issue747.integ.snapshot/integ.json
  test/integ/issue991.integ.snapshot/Claude37Test.assets.json
  test/integ/issue991.integ.snapshot/Claude37TestIntegDefaultTestDeployAssert7B904896.assets.json
  test/integ/issue991.integ.snapshot/cdk.out
  test/integ/issue991.integ.snapshot/integ.json
  test/integ/issue991.integ.snapshot/manifest.json
  test/integ/issue991.integ.snapshot/tree.json
  test/integ/kendra-genai.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/integ/kendra-genai.integ.snapshot/aws-cdk-bedrock-prompt-kendra-integ-test.assets.json
  test/integ/kendra-genai.integ.snapshot/integ.json
  test/integ/prompt-router.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/integ/prompt-router.integ.snapshot/aws-cdk-bedrock-prompt-router-integ-test.assets.json
  test/integ/prompt-router.integ.snapshot/integ.json
  test/patterns/gen-ai/aws-aoss-cw-dashboard/integ-tests/aws-aoss-cw-dashboard.integ.snapshot/ServiceTestDefaultTestDeployAssertE49B1ECE.assets.json
  test/patterns/gen-ai/aws-aoss-cw-dashboard/integ-tests/aws-aoss-cw-dashboard.integ.snapshot/aws-cdk-aoss-dashboard-integ-test.assets.json
  test/patterns/gen-ai/aws-aoss-cw-dashboard/integ-tests/aws-aoss-cw-dashboard.integ.snapshot/integ.json
  yarn.lock
Labels: distinguished-contributor

#1058 feat(bda): added cors policy to bda buckets
  src/patterns/gen-ai/aws-bedrock-data-automation/index.ts
Labels: star-contributor

#1061 fix(bda): updated bda construct with schema file upload changes
  lambda/aws-bedrock-data-automation/bda_blueprint/lambda.py
  lambda/aws-bedrock-data-automation/bda_blueprint/manage_blueprint.py
  lambda/aws-bedrock-data-automation/bda_project/lambda.py
Labels: star-contributor

#1069 chore(doc): update bedrock documentation
  src/cdk-lib/amazonaurora/README.md
  src/cdk-lib/bedrock/README.md
  src/cdk-lib/bedrock/agents/README.md
  src/cdk-lib/bedrock/data-sources/README.md
  src/cdk-lib/bedrock/guardrails/README.md
  src/cdk-lib/bedrock/inference-profiles/README.md
  src/cdk-lib/bedrock/knowledge-bases/README.md
  src/cdk-lib/bedrock/models_readme.md
  src/cdk-lib/bedrock/prompts/README.md
Labels: distinguished-contributor

#1076 chore(guardrails): Add support for input/output modalities in Bedrock guardrails content filter
  .projen/deps.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  apidocs/@cdklabs/namespaces/bedrock/README.md
  apidocs/@cdklabs/namespaces/bedrock/enumerations/ModalityType.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/ContentFilter.md
  package.json
  src/cdk-lib/bedrock/guardrails/README.md
  src/cdk-lib/bedrock/guardrails/guardrail-filters.ts
  yarn.lock
Labels: distinguished-contributor

#1078 feat(bedrock): add mistral models
  apidocs/@cdklabs/namespaces/bedrock/classes/BedrockFoundationModel.md
  src/cdk-lib/bedrock/models.ts
Labels: admired-contributor

#1079 feat(bedrock): add support for MongoDbAtlas and supplemental data storage in KB
  apidocs/@cdklabs/namespaces/bedrock/README.md
  apidocs/@cdklabs/namespaces/bedrock/classes/SupplementalDataStorageLocation.md
  apidocs/@cdklabs/namespaces/bedrock/classes/VectorKnowledgeBase.md
  apidocs/@cdklabs/namespaces/bedrock/enumerations/SupplementalDataStorageLocationType.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/SupplementalDataStorageS3Config.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/VectorKnowledgeBaseProps.md
  apidocs/@cdklabs/namespaces/bedrock/type-aliases/SupplementalDataStorageLocationConfig.md
  apidocs/@cdklabs/namespaces/mongodbAtlas/README.md
  apidocs/@cdklabs/namespaces/mongodbAtlas/classes/MongoDBAtlasVectorStore.md
  apidocs/@cdklabs/namespaces/mongodbAtlas/interfaces/MongoDBAtlasVectorStoreProps.md
  apidocs/@cdklabs/namespaces/mongodbAtlas/interfaces/MongoDbAtlasFieldMapping.md
  apidocs/README.md
  src/cdk-lib/bedrock/data-sources/README.md
  src/cdk-lib/bedrock/index.ts
  src/cdk-lib/bedrock/knowledge-bases/README.md
  src/cdk-lib/bedrock/knowledge-bases/supplemental-data-storage.ts
  src/cdk-lib/bedrock/knowledge-bases/vector-knowledge-base.ts
  src/cdk-lib/bedrock/models_readme.md
  src/cdk-lib/mongodb-atlas/README.md
  src/cdk-lib/mongodb-atlas/index.ts
  src/cdk-lib/mongodb-atlas/mongodb-atlas-vector-store.ts
  src/index.ts
  test/cdk-lib/bedrock/knowledge-base.test.ts
Labels: distinguished-contributor

#1082 feat(bedrock): add aurora kb sql statement
  lambda/amazon-aurora-pgvector-custom-resources/custom_resources/amazon_aurora_pgvector.py
Labels: admired-contributor

#1096 feat(bedrock): expose bda parsing strategy for data sources
  apidocs/@cdklabs/namespaces/bedrock/README.md
  apidocs/@cdklabs/namespaces/bedrock/classes/ParsingStrategy.md
  apidocs/@cdklabs/namespaces/bedrock/enumerations/ParsingStrategyType.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/ConfluenceDataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/ConfluenceDataSourceProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/CustomDataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/CustomDataSourceProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/DataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/FoundationModelParsingStrategyProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/S3DataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/S3DataSourceProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/SalesforceDataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/SalesforceDataSourceProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/SharePointDataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/SharePointDataSourceProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/WebCrawlerDataSourceAssociationProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/WebCrawlerDataSourceProps.md
  src/cdk-lib/bedrock/data-sources/README.md
  src/cdk-lib/bedrock/data-sources/base-data-source.ts
  src/cdk-lib/bedrock/data-sources/parsing.ts
  src/cdk-lib/bedrock/knowledge-bases/README.md
  test/cdk-lib/bedrock/data-sources/s3-data-source.test.ts
Labels: distinguished-contributor

#1101 fix(bda): updated blueprint schema, added schema support
  lambda/aws-bedrock-data-automation/bda_blueprint/create_schema.py
  lambda/aws-bedrock-data-automation/bda_blueprint/custom_blueprint_schema.py
  lambda/aws-bedrock-data-automation/bda_blueprint/lambda.py
  lambda/aws-bedrock-data-automation/bda_project/lambda.py
  lambda/aws-bedrock-data-automation/bda_project/project_config.py
  lambda/aws-bedrock-data-automation/data_processing/data_processing.py
  lambda/aws-bedrock-data-automation/data_processing/lambda.py
  lambda/aws-bedrock-data-automation/data_result/data_automation_result.py
  lambda/aws-bedrock-data-automation/data_result/lambda.py
  layer/requirements.txt
  src/patterns/gen-ai/aws-bedrock-data-automation/README.md
Labels: star-contributor

#1097 feat(bedrock): add support for os managed cluster and guardrails latest properties
  .projen/deps.json
  .projenrc.ts
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  apidocs/@cdklabs/namespaces/bedrock/README.md
  apidocs/@cdklabs/namespaces/bedrock/classes/Guardrail.md
  apidocs/@cdklabs/namespaces/bedrock/classes/VectorKnowledgeBase.md
  apidocs/@cdklabs/namespaces/bedrock/enumerations/GuardrailAction.md
  apidocs/@cdklabs/namespaces/bedrock/enumerations/ManagedWordFilterType.md
  apidocs/@cdklabs/namespaces/bedrock/enumerations/VectorStoreType.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/ContentFilter.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/ContextualGroundingFilter.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/CustomTopicProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/GuardrailProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/ManagedWordFilter.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/PIIFilter.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/RegexFilter.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/VectorKnowledgeBaseProps.md
  apidocs/@cdklabs/namespaces/bedrock/interfaces/WordFilter.md
  apidocs/@cdklabs/namespaces/mongodbAtlas/classes/MongoDBAtlasVectorStore.md
  apidocs/@cdklabs/namespaces/mongodbAtlas/interfaces/MongoDBAtlasVectorStoreProps.md
  apidocs/@cdklabs/namespaces/opensearchmanagedcluster/README.md
  apidocs/@cdklabs/namespaces/opensearchmanagedcluster/classes/OpenSearchManagedClusterVectorStore.md
  apidocs/@cdklabs/namespaces/opensearchmanagedcluster/interfaces/OpenSearchFieldMapping.md
  apidocs/@cdklabs/namespaces/opensearchmanagedcluster/interfaces/OpenSearchManagedClusterVectorStoreProps.md
  apidocs/README.md
  package.json
  src/cdk-lib/bedrock/guardrails/README.md
  src/cdk-lib/bedrock/guardrails/guardrail-filters.ts
  src/cdk-lib/bedrock/guardrails/guardrails.ts
  src/cdk-lib/bedrock/knowledge-bases/README.md
  src/cdk-lib/bedrock/knowledge-bases/vector-knowledge-base.ts
  src/cdk-lib/mongodb-atlas/mongodb-atlas-vector-store.ts
  src/cdk-lib/opensearchmanagedcluster/README.md
  src/cdk-lib/opensearchmanagedcluster/index.ts
  src/cdk-lib/opensearchmanagedcluster/opensearch-managed-cluster-vector-store.ts
  src/index.ts
  test/cdk-lib/bedrock/guardrails.test.ts
  test/cdk-lib/bedrock/knowledge-base.test.ts
  test/cdk-lib/opensearchmanagedcluster/opensearchmanagedcluster.test.ts
  test/integ/guardrails.integ.snapshot/aws-cdk-bedrock-agents-integ-test.assets.json
  test/integ/guardrails.integ.snapshot/aws-cdk-bedrock-agents-integ-test.template.json
  test/integ/guardrails.integ.ts
  yarn.lock
Labels: distinguished-contributor
